version = 1

[values]
Image = "virter-hello-world"

[[steps]]
[steps.container]
image = "{{.Image}}"
pull = "Never"
# example of how to copy a file from the container after provisioning is finished:
[steps.container.copy]
source = "/entry.sh"
dest = "/tmp/"
